#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 7

#define VIAL_ENCODER_DEFAULT {KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}

#define VIAL_ENCODER_KEYCODE_DELAY 10

//#define VIAL_KEYBOARD_UID {0xB3, 0x30, 0xE4, 0x75, 0xF9, 0x3A, 0x9B, 0x18}
#define VIAL_KEYBOARD_UID {0x85, 0x1B, 0x7E, 0x06, 0xF2, 0xE8, 0x03, 0x93}

#define VIAL_INSECURE
